version: "3.9"

services:
  db:
    image: postgres
    container_name: FinAPI
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api